"""
BF3 molecular geometry and D3h symmetry operations.

This module contains BF3-specific scientific information only.

Cartesian convention:
    r' = M @ r

Fixed coordinate frame:
    - BF3 is planar in the xy-plane.
    - B is at the origin.
    - z-axis is perpendicular to the molecular plane.
    - F atoms are arranged symmetrically in the xy-plane.

The actual transformation matrices are generated by the universal
transformation engine in transformations.py.
"""

from __future__ import annotations

import math
from typing import Any

import numpy as np

from .transformations import build_transformation_matrix


# ---------------------------------------------------------------------------
# BF3 geometry
# ---------------------------------------------------------------------------

BF3_NAME = "BF3"
BF3_FORMULA = "BF3"
BF3_POINT_GROUP = "D3h"

# Convenient normalized B-F bond length.
BF_BOND_LENGTH = 1.0

# Three F atoms separated by 120 degrees in the xy-plane.
BF3_COORDINATES: dict[str, list[float]] = {
    "B": [0.0, 0.0, 0.0],
    "F1": [
        BF_BOND_LENGTH,
        0.0,
        0.0,
    ],
    "F2": [
        BF_BOND_LENGTH * math.cos(math.radians(120.0)),
        BF_BOND_LENGTH * math.sin(math.radians(120.0)),
        0.0,
    ],
    "F3": [
        BF_BOND_LENGTH * math.cos(math.radians(240.0)),
        BF_BOND_LENGTH * math.sin(math.radians(240.0)),
        0.0,
    ],
}


# ---------------------------------------------------------------------------
# BF3 symmetry operations
# ---------------------------------------------------------------------------

def get_bf3_operations() -> list[dict[str, Any]]:
    """
    Return the symmetry operations of BF3 in the fixed Cartesian frame.

    D3h contains 12 symmetry operations:

        E
        2C3
        3C2'
        sigma_h
        2S3
        3sigma_v

    Individual operations are returned explicitly so that each operation
    can have its own Cartesian transformation matrix.
    """
    operations: list[dict[str, Any]] = [
        # Identity
        {
            "id": "E",
            "symbol": "E",
            "type": "identity",
        },

        # C3 rotations around z
        {
            "id": "C3_1",
            "symbol": "C3",
            "type": "rotation",
            "axis": [0.0, 0.0, 1.0],
            "angle_deg": 120.0,
        },
        {
            "id": "C3_2",
            "symbol": "C3^2",
            "type": "rotation",
            "axis": [0.0, 0.0, 1.0],
            "angle_deg": 240.0,
        },

        # Three C2' axes in the molecular plane.
        #
        # The first axis is chosen along +x.
        # The other two are obtained by 120-degree rotations in the xy-plane.
        {
            "id": "C2p_1",
            "symbol": "C2'",
            "type": "rotation",
            "axis": [1.0, 0.0, 0.0],
            "angle_deg": 180.0,
        },
        {
            "id": "C2p_2",
            "symbol": "C2'",
            "type": "rotation",
            "axis": [
                math.cos(math.radians(120.0)),
                math.sin(math.radians(120.0)),
                0.0,
            ],
            "angle_deg": 180.0,
        },
        {
            "id": "C2p_3",
            "symbol": "C2'",
            "type": "rotation",
            "axis": [
                math.cos(math.radians(240.0)),
                math.sin(math.radians(240.0)),
                0.0,
            ],
            "angle_deg": 180.0,
        },

        # Horizontal reflection: molecular plane xy.
        {
            "id": "sigma_h",
            "symbol": "σh",
            "type": "reflection",
            "plane_normal": [0.0, 0.0, 1.0],
        },

        # S3 operations:
        # S3 = sigma_h C3
        {
            "id": "S3_1",
            "symbol": "S3",
            "type": "improper_rotation",
            "axis": [0.0, 0.0, 1.0],
            "angle_deg": 120.0,
        },
        {
            "id": "S3_2",
            "symbol": "S3^5",
            "type": "improper_rotation",
            "axis": [0.0, 0.0, 1.0],
            "angle_deg": 240.0,
        },

        # Three vertical reflection planes.
        #
        # Each plane contains the z-axis and one C2' axis.
        # Therefore its normal lies in the xy-plane and is perpendicular
        # to the corresponding C2' axis.
        {
            "id": "sigma_v_1",
            "symbol": "σv",
            "type": "reflection",
            "plane_normal": [0.0, 1.0, 0.0],
        },
        {
            "id": "sigma_v_2",
            "symbol": "σv",
            "type": "reflection",
            "plane_normal": [
                -math.sin(math.radians(120.0)),
                math.cos(math.radians(120.0)),
                0.0,
            ],
        },
        {
            "id": "sigma_v_3",
            "symbol": "σv",
            "type": "reflection",
            "plane_normal": [
                -math.sin(math.radians(240.0)),
                math.cos(math.radians(240.0)),
                0.0,
            ],
        },
    ]

    return operations


# ---------------------------------------------------------------------------
# Geometry access
# ---------------------------------------------------------------------------

def get_bf3_geometry() -> dict[str, Any]:
    """Return the BF3 molecular geometry."""
    return {
        "name": BF3_NAME,
        "formula": BF3_FORMULA,
        "point_group": BF3_POINT_GROUP,
        "coordinates": {
            atom: coordinates.copy()
            for atom, coordinates in BF3_COORDINATES.items()
        },
    }


# ---------------------------------------------------------------------------
# Transformation matrices
# ---------------------------------------------------------------------------

def generate_bf3_matrices() -> dict[str, dict[str, Any]]:
    """
    Generate Cartesian transformation matrices for all BF3 operations.

    Matrix construction is delegated entirely to the universal
    transformation engine.
    """
    matrices: dict[str, dict[str, Any]] = {}

    for operation in get_bf3_operations():
        operation_id = operation["id"]

        result = build_transformation_matrix(operation)

        if not result["success"]:
            raise ValueError(
                f"Failed to construct matrix for {operation_id}: "
                f"{result['error']['message']}"
            )

        matrices[operation_id] = result

    return matrices


# ---------------------------------------------------------------------------
# Coordinate transformation helpers
# ---------------------------------------------------------------------------

def transform_bf3_coordinates(
    matrix: list[list[float]],
) -> dict[str, list[float]]:
    """
    Apply a Cartesian transformation to every BF3 atom.

    This function does not decide whether the operation is a symmetry
    operation. It only performs the mathematical coordinate transformation.
    """
    transformation = np.asarray(matrix, dtype=float)

    if transformation.shape != (3, 3):
        raise ValueError("matrix must be a 3x3 matrix.")

    transformed_coordinates: dict[str, list[float]] = {}

    for atom, coordinate in BF3_COORDINATES.items():
        vector = np.asarray(coordinate, dtype=float)
        transformed = transformation @ vector
        transformed_coordinates[atom] = transformed.tolist()

    return transformed_coordinates


# ---------------------------------------------------------------------------
# Coordinate matching
# ---------------------------------------------------------------------------

def _coordinates_match(
    first: list[float],
    second: list[float],
    tolerance: float = 1e-8,
) -> bool:
    """Check whether two Cartesian coordinates are numerically equivalent."""
    return bool(
        np.allclose(
            np.asarray(first, dtype=float),
            np.asarray(second, dtype=float),
            atol=tolerance,
            rtol=tolerance,
        )
    )


def _same_atom_set_after_transformation(
    transformed: dict[str, list[float]],
    tolerance: float = 1e-8,
) -> bool:
    """
    Check whether transformed BF3 coordinates correspond to the original
    coordinates while preserving atom identity by element.

    Since all three peripheral atoms are fluorine, F1/F2/F3 may permute.
    """
    original_boron = BF3_COORDINATES["B"]

    if not _coordinates_match(
        transformed["B"],
        original_boron,
        tolerance=tolerance,
    ):
        return False

    original_fluorines = [
        BF3_COORDINATES["F1"],
        BF3_COORDINATES["F2"],
        BF3_COORDINATES["F3"],
    ]

    transformed_fluorines = [
        transformed["F1"],
        transformed["F2"],
        transformed["F3"],
    ]

    unmatched = original_fluorines.copy()

    for transformed_f in transformed_fluorines:
        match_index = None

        for index, original_f in enumerate(unmatched):
            if _coordinates_match(
                transformed_f,
                original_f,
                tolerance=tolerance,
            ):
                match_index = index
                break

        if match_index is None:
            return False

        unmatched.pop(match_index)

    return len(unmatched) == 0


def is_bf3_symmetry_operation(
    operation: dict[str, Any],
    tolerance: float = 1e-8,
) -> dict[str, Any]:
    """
    Determine whether a supplied transformation is a BF3 symmetry operation.

    The check is geometric:
        1. Build the Cartesian transformation matrix.
        2. Transform all BF3 coordinates.
        3. Check whether the transformed atom set matches the original set.
    """
    result = build_transformation_matrix(operation)

    if not result["success"]:
        return {
            "success": False,
            "is_symmetry": False,
            "operation": operation,
            "matrix": None,
            "transformed_coordinates": None,
            "error": result["error"],
        }

    matrix = result["matrix"]

    transformed_coordinates = transform_bf3_coordinates(matrix)

    is_symmetry = _same_atom_set_after_transformation(
        transformed_coordinates,
        tolerance=tolerance,
    )

    return {
        "success": True,
        "is_symmetry": is_symmetry,
        "operation": operation,
        "matrix": matrix,
        "transformed_coordinates": transformed_coordinates,
        "error": None,
    }


# ---------------------------------------------------------------------------
# BF3 scientific definition
# ---------------------------------------------------------------------------

def get_bf3_symmetry_data() -> dict[str, Any]:
    """
    Return the complete BF3 symmetry definition.

    This is the main scientific entry point for BF3-specific symmetry data.
    """
    operations = get_bf3_operations()
    matrices = generate_bf3_matrices()

    return {
        "molecule": {
            "name": BF3_NAME,
            "formula": BF3_FORMULA,
            "point_group": BF3_POINT_GROUP,
            "coordinates": {
                atom: coordinates.copy()
                for atom, coordinates in BF3_COORDINATES.items()
            },
        },
        "operations": operations,
        "matrices": matrices,
    }